# Generated by Django 2.2.1 on 2019-05-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0002_auto_20190523_0649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XyzUser',
        ),
    ]
