# Generated by Django 2.2.1 on 2019-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0003_delete_xyzuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsersTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=110)),
                ('phone_no', models.BigIntegerField()),
                ('login_email', models.CharField(max_length=110)),
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(max_length=110)),
                ('password', models.CharField(max_length=110)),
                ('last_login', models.DateTimeField()),
                ('designation', models.CharField(max_length=110)),
                ('personal_email', models.CharField(max_length=110)),
                ('access', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'admin_users_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersPunam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users_punam',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
