# Generated by Django 2.2.1 on 2019-05-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0004_auto_20190524_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCommentsTbl',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_comments_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
    ]
